"use client";

import React from "react";
import {
  DocSection,
  DocSubsection,
  DocParagraph,
  CodeBlock,
  InlineCode,
  DocTable,
  DocNote,
} from "../DocSection";

export function NodesSection() {
  return (
    <>
      <DocSection title="Nodes">
        <DocParagraph>
          Nodes are the primary entities in a Verdant diagram. Each node has a type and a unique ID.
        </DocParagraph>
      </DocSection>

      <DocSection title="Inline Declaration">
        <DocParagraph>
          The simplest form — type and ID on one line, no properties:
        </DocParagraph>
        <CodeBlock
          code={`server api
database users-db
gateway main-gateway`}
        />
      </DocSection>

      <DocSection title="Block Declaration">
        <DocParagraph>
          Add a colon to open a property block:
        </DocParagraph>
        <CodeBlock
          code={`server api:
  label: "API Gateway"
  color: #52B788
  size: lg
  glow: true`}
        />
      </DocSection>

      <DocSection title="Node IDs">
        <ul className="space-y-2 list-disc list-inside ml-4">
          <li className="font-body text-base leading-7 text-[color:var(--text-secondary)]">
            Must start with a letter or underscore
          </li>
          <li className="font-body text-base leading-7 text-[color:var(--text-secondary)]">
            Can contain letters, digits, hyphens, dots, and underscores
          </li>
          <li className="font-body text-base leading-7 text-[color:var(--text-secondary)]">
            Dots are used for qualified names within groups (e.g., <InlineCode>backend.api</InlineCode>)
          </li>
          <li className="font-body text-base leading-7 text-[color:var(--text-secondary)]">
            Must be unique within the document
          </li>
        </ul>
        <CodeBlock
          code={`server web-server          # hyphenated
server my_api              # underscored
server backend.api         # qualified (usually auto-generated by groups)`}
        />
      </DocSection>

      <DocSection title="Node Properties">
        <DocTable
          headers={["Property", "Type", "Description"]}
          rows={[
            ["label", "string", "Display text. Defaults to the node ID."],
            ["color", "hex string", "Node color. #RGB, #RRGGBB, or #RRGGBBAA."],
            ["size", "enum", "Visual size: xs, sm, md, lg, xl"],
            ["glow", "boolean", "Enable glow effect"],
            ["icon", "string", "Icon identifier"],
            ["position", "x,y,z", "Manual position in world space"],
            ["shape", "enum", "Override the default shape for this node type"],
            ["status", "enum", "Health indicator: healthy, warning, error, unknown"],
            ["opacity", "number", "Transparency (0.0 – 1.0)"],
            ["scale", "number", "Size multiplier (positive number)"],
            ["enter", "enum", "Mount animation: fade, scale, slide"],
            ["exit", "enum", "Unmount animation: fade, scale, slide"],
            ["animation-duration", "number", "Animation duration in milliseconds"],
          ]}
        />
      </DocSection>

      <DocSection title="Complete Example">
        <CodeBlock
          code={`server api:
  label: "API Gateway"
  color: #52B788
  size: lg
  status: healthy
  shape: diamond
  glow: true
  position: 0, 2, 0
  enter: scale
  exit: fade
  animation-duration: 400
  badge top-right: "3"
  badge bottom-left: "icon:shield"
  port http-in: top
  port http-out: bottom`}
        />
      </DocSection>

      <DocSection title="Badges">
        <DocParagraph>
          Badges are small overlays at node corners. The position must be one of: <InlineCode>top-right</InlineCode>, <InlineCode>top-left</InlineCode>, <InlineCode>bottom-right</InlineCode>, <InlineCode>bottom-left</InlineCode>
        </DocParagraph>
        <CodeBlock
          code={`server api:
  badge top-right: "5"            # numeric badge (circular)
  badge top-left: "icon:shield"   # icon badge (emoji)
  badge bottom-right: "LIVE"      # text badge (pill-shaped)`}
        />
        <DocTable
          headers={["Badge Type", "Example", "Rendering"]}
          rows={[
            ["Numeric (1–3 digits)", <InlineCode key="1">"5"</InlineCode>, "Circular badge"],
            ["Icon", <InlineCode key="2">"icon:shield"</InlineCode>, "Emoji icon (🛡️)"],
            ["Text", <InlineCode key="3">"LIVE"</InlineCode>, "Pill-shaped label"],
          ]}
        />
      </DocSection>
    </>
  );
}
